[versions]
agp = "8.1.4"
kotlin = "1.9.23"
core-ktx = "1.17.0"
lifecycle-runtime-ktx = "2.10.0"
activity-compose = "1.12.2"
compose-bom = "2026.01.00"
compose-ui = "ui"
compose-ui-graphics = "ui-graphics"
compose-ui-tooling = "ui-tooling"
compose-ui-tooling-preview = "ui-tooling-preview"
compose-ui-test-junit4 = "1.10.1"
compose-ui-test-manifest = "1.10.1"
compose-material3 = "material3"
junit = "4.13.2"
androidx-test-ext-junit = "1.3.0"
espresso-core = "3.7.0"
support-annotations = "28.0.0"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose-ui-graphics" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
support-annotations = { group = "com.android.support", name = "support-annotations", version.ref = "support-annotations" }

compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-ui-test-manifest" }
[bundles]
compose = ["compose-ui", "compose-ui-graphics", "compose-ui-tooling-preview", "compose-material3"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }