[versions]
agp = "8.2.2"
kotlin = "2.1.0"
ksp = "2.1.0-1.0.29"
core-ktx = "1.12.0"
lifecycle-runtime-ktx = "2.6.2"
activity-compose = "1.8.0"
compose-bom = "2023.10.01"
compose-ui = "ui"
compose-ui-graphics = "ui-graphics"
compose-ui-tooling = "ui-tooling"
compose-ui-tooling-preview = "ui-tooling-preview"
compose-ui-test-junit4 = "1.10.1"
compose-ui-test-manifest = "1.10.1"
compose-material3 = "material3"
junit = "4.13.2"
androidx-test-ext-junit = "1.3.0"
espresso-core = "3.7.0"
support-annotations = "28.0.0"
play-services-location = "21.3.0"
navigation-runtime-android = "2.9.6"
runtime = "1.0.0-alpha10"
remote-creation-compose = "1.0.0-alpha03"
transport-runtime = "4.0.0"
firebase-auth-ktx = "24.0.1"
databinding-adapters = "9.0.1"
core-animation = "1.0.0"
room = "2.6.1"
room-common-jvm = "2.8.4"
room-runtime-android = "2.8.4"


[libraries]

androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
gms-play-services-location = { module = "com.google.android.gms:play-services-location" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose-ui-graphics" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
support-annotations = { group = "com.android.support", name = "support-annotations", version.ref = "support-annotations" }


compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-ui-test-manifest" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "play-services-location" }
androidx-navigation-runtime-android = { group = "androidx.navigation", name = "navigation-runtime-android", version.ref = "navigation-runtime-android" }
androidx-runtime = { group = "androidx.xr.runtime", name = "runtime", version.ref = "runtime" }
androidx-remote-creation-compose = { group = "androidx.compose.remote", name = "remote-creation-compose", version.ref = "remote-creation-compose" }
transport-runtime = { group = "com.google.android.datatransport", name = "transport-runtime", version.ref = "transport-runtime" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebase-auth-ktx" }
androidx-databinding-adapters = { group = "androidx.databinding", name = "databinding-adapters", version.ref = "databinding-adapters" }
androidx-core-animation = { group = "androidx.core", name = "core-animation", version.ref = "core-animation" }
androidx-room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "room-common-jvm" }
androidx-room-runtime-android = { group = "androidx.room", name = "room-runtime-android", version.ref = "room-runtime-android" }
[bundles]
compose = ["compose-ui", "compose-ui-graphics", "compose-ui-tooling-preview", "compose-material3"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }